server:
    port: 8081

system:
    socket:
        ip: 114.242.105.153
        port: 10011

file:
     downFilePath: d:/Data/down

spring:
     application:
         name: qrfileservice
     datasource:
         url: jdbc:mysql://120.132.33.248:13565/qrfilemanage?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
         username: root
         password: Cec@123456
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver
         # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
         initialSize: 50
         minIdle: 5
         maxActive: 1000
         # 配置获取连接等待超时的时间
         maxWait: 60000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         timeBetweenEvictionRunsMillis: 60000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         minEvictableIdleTimeMillis: 300000
         validationQuery: SELECT 1 FROM DUAL
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         # 打开PSCache，并且指定每个连接上PSCache的大小
         poolPreparedStatements: true
         maxPoolPreparedStatementPerConnectionSize: 20
         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
         filters: stat,wall,log4j
         # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
         connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
         # 合并多个DruidDataSource的监控数据
         useGlobalDataSourceStat: false
         # 连接泄漏处理  用来关闭长时间不使用的连接
         removeAbandoned: true
         # 300秒，也就是5分钟
         removeAbandonedTimeout: 300


logging:
   level:
         root: INFO
         org:
            springframework:
                    web: DEBUG
            apache:
                    ibatis: DEBUG

log_path: d:/data/qrfileservice/logs



